### ISSUE TITLE
No sé debe recargar 

### ISSUE THREAD

**Issue by canek-pelaez** [arturoglcc/financial_project#26]
No sé debe recargar después de agregar

**Comment by KevinJGard** [comment]
[Debt Table commit](https://github.com/arturoglcc/financial_project/commit/84e1cfd14a04dd1a9ba1bba111a2ea3589d2b6fe)   
[Income Table commit](https://github.com/arturoglcc/financial_project/commit/533fb5d613ad0845c3f0d4c7cba706fd232024c5)   
[Outlay Table commit](https://github.com/arturoglcc/financial_project/commit/5a49c1af94a11c54914a9aad1e7c6439a8ad1b7b)
